name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    steps:
      # Output PR author?
      - run: echo ${{ github.event.pull_request.user.login }}
      # - uses: hmarr/auto-approve-action@v3
      #   with:
      #     review-message: 'Automatically approved PR. ✅'
