# https://github.com/marketplace/actions/auto-approve
name: Auto approve

on:
  pull_request:
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: hmarr/auto-approve-action@v3
        if: github.actor == 'hanspagel' && github.ref == 'refs/heads/changeset-release/main'
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
