name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write

    if: github.actor == 'github-actions[bot]'

    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: 'Automatically approved PR. ✅'
