# https://github.com/marketplace/actions/auto-approve
name: Auto approve

on:
  pull_request:
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write

    steps:
      - run: echo "github.actor ${{ github.actor }}"
      - run: echo "github.event.pull_request.user.login ${{ github.event.pull_request.user.login }}"
      - uses: hmarr/auto-approve-action@v3
        if: github.actor == 'github-actions[bot]' || github.event.pull_request.user.login == 'github-actions[bot]'
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
